### ISSUE TITLE
Suggestion for return type

### ISSUE THREAD

**Issue by StNekroman** [delight-rpc/worker-threads#3]
`[client: DelightRPC.ClientProxy<IAPI>, close: () => void] `
That tuple in return type, I siggest to pack it to one object

```
{
  api: DelightRPC.ClientProxy<IAPI>;
  close() : void;
}
```

So consumers of that should keep two refs and maintain them.
Just
```
const client = createClient(...);
client.api.apiCall(...);
client.close()
```
Without having two refs and remember about them.

**Comment by StNekroman** [comment]
Bonus: with single return type interface - it's extremelly easy to extend that any time and add new methods/props.

**Comment by BlackGlory** [comment]
Thank you for your suggestion.
The current return type is inspired by react-hooks, mainly because of the need for custom variable names.

Returning objects is very ugly in this scenario compared to returning tuples:
```ts
const { proxy: xxxAPI, close: closeXXX } = createClient(...)

const [xxxAPI, closeXXX] = createClient(...)
```
Of course, you can use it like `client.proxy.callXXX`,  but it's a bit cumbersome for me.

Considering that there are no more values to return now, the API doesn't need to change.
If there is a third value to return in the future, I will definitely return an object.

**Comment by StNekroman** [comment]
Why cumbersome?
Just returning obj wrapper.
Who needs - always can unbox particular field from it.
`const { xxxAPI } = createClient(...)`
While I can't image, why somebody don't need close() - it's always good to close allocated resources when not needed.

**Comment by BlackGlory** [comment]
It is possible not to use `close`, if the program is terminated together with `Worker`.
The point is that it is good to return a tuple with only 2 values, at least better than returning object, so there is no need to make a breaking change for it.
